[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_DISABLE_WINDOWDECORATION=1

[Theme]
Current=breeze
CursorTheme=breeze_cursors

[Users]
MinimumUid=1000
MaximumUid=60513
HideEmptyUsers=true
